Creation of new TPC Offline HTML QA module
sPHENIX-Collaboration/QAhtml pull request #14
Opened 2024-05-21 00:32 UTC by rosstom2232

New module that writes html output for the QA histograms produced by TpcClusterQA and TpcChanQA modules
Default is to just write the ClusterQA output for now, but that can be changed if need be

2024-05-21 13:51 UTC, osbornjd requested changes
We shouldn't need the sPhenixStyle files in there - shouldn't we be able to access them from the nightly build?

Try doing a git pull and making sure that your changes mesh well with some of the renaming Chris did over the weekend

2024-05-21 13:51 UTC, osbornjd commented on subsystems/tpc/macros/draw_calo.C
> +  OnlProdDraw *ex = new TPCDraw();
Chris made some changes to rename this to `QADraw` - can you do a git pull and retest to make sure everything still works

2024-05-21 13:51 UTC, osbornjd commented on subsystems/tpc/macros/draw_calo.C
> +void draw_calo(const char *rootfile) {
Lets rename this to draw_tpc

2024-05-21 13:51 UTC, osbornjd commented on subsystems/tpc/Makefile.am
> +libonlprodcalo_la_LIBADD = \
Lets rename this library to something like `qadrawtpc`

2024-05-22 01:07 UTC, rosstom2232 commented
Just saw Joe's comments, I'll fix those now!

2024-05-22 18:29 UTC, merged